import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { App } from "./App";
import { ErrorBoundary } from "./components/ErrorBoundary";
import "./styles.css";
import "./collaboration.css";
import "./product.css";
import "./performance.css";
import "./launch-polish.css";
import "./release-finish.css";
import "./mobile-compat.css";
import "./room-v2.css";
import "./brand-refresh.css";
createRoot(document.getElementById("root")!).render(<StrictMode><ErrorBoundary><App/></ErrorBoundary></StrictMode>);
