import AgoraRTC,{type ConnectionState,type IAgoraRTCClient,type ILocalAudioTrack,type ILocalTrack,type ILocalVideoTrack} from "agora-rtc-sdk-ng";
import { BarChart3, Check, ChevronDown, Clipboard, Eye, Mic, MicOff, MonitorUp, Radio, Square, Users, WifiOff } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { Logo } from "../components/Logo";
import { StatsPanel } from "../components/StatsPanel";
import { StatusPill } from "../components/StatusPill";
import { connectSocket } from "../services/socket";
import { displayConstraints,readAgoraStats } from "../services/webrtc";
import type { AgoraCredentials,FrameRate,Quality,RoomAck,StreamStats,TokenAck } from "../types";

type LocalAgoraTrack=ILocalVideoTrack|ILocalAudioTrack;
const activeTrack=(track:MediaStreamTrack|undefined)=>!!track&&track.readyState!=="ended";
export function BroadcasterPage(){
  const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),clientRef=useRef<IAgoraRTCClient|null>(null),localTracksRef=useRef<LocalAgoraTrack[]>([]),credentialsRef=useRef<AgoraCredentials|null>(null),tokenRef=useRef(""),liveRef=useRef(false),agoraReadyRef=useRef(false),publishedClientRef=useRef<IAgoraRTCClient|null>(null);
  const [roomId,setRoomId]=useState(""),[agora,setAgora]=useState<AgoraCredentials|null>(null),[viewers,setViewers]=useState(0),[quality,setQuality]=useState<Quality>("1080p"),[fps,setFps]=useState<FrameRate>(30),[live,setLive]=useState(false),[agoraReady,setAgoraReady]=useState(false),[muted,setMuted]=useState(false),[copied,setCopied]=useState(false),[connection,setConnection]=useState("Conectando"),[error,setError]=useState(""),[stats,setStats]=useState<StreamStats|null>(null),[showStats,setShowStats]=useState(false);
  const roomUrl=roomId?`${location.origin}/?room=${encodeURIComponent(roomId)}`:"";
  useEffect(()=>{liveRef.current=live;},[live]);
  useEffect(()=>{if(!agora)return;let active=true;agoraReadyRef.current=false;setAgoraReady(false);const client=AgoraRTC.createClient({mode:"live",codec:"vp8"});clientRef.current=client;const publishCurrent=async()=>{const stream=streamRef.current,video=stream?.getVideoTracks().find(activeTrack),tracks=localTracksRef.current;if(!active||!liveRef.current||!stream||!video||!tracks.length)return;const missing=tracks.filter(track=>!client.localTracks.includes(track as ILocalTrack));if(!missing.length){publishedClientRef.current=client;return;}try{await client.publish(missing);publishedClientRef.current=client;}catch(cause){console.error("Agora screen republish error",cause);setError("A transmissão continua ativa, mas não foi possível republicar sua tela após a reconexão.");}};const renew=async(rejoin=false)=>{try{const renewed=await new Promise<string>((resolve,reject)=>connectSocket().emit("renew-agora-token",{roomId},(ack:TokenAck)=>ack.ok&&ack.agoraToken?resolve(ack.agoraToken):reject(new Error(ack.error||"Token Agora inválido."))));if(rejoin&&client.connectionState==="DISCONNECTED")await client.join(agora.agoraAppId,agora.agoraChannel,renewed,agora.agoraUid);else await client.renewToken(renewed);if(credentialsRef.current)credentialsRef.current={...credentialsRef.current,agoraToken:renewed};}catch(cause){console.error("Agora token renewal error",cause);setError("Não foi possível renovar a conexão com o servidor de transmissão.");}};const onConnection=(state:ConnectionState)=>{if(!active)return;if(state==="CONNECTED"){agoraReadyRef.current=true;setAgoraReady(true);setConnection("Conectado");void publishCurrent();}else{agoraReadyRef.current=false;setAgoraReady(false);if(state==="CONNECTING"||state==="RECONNECTING"||state==="DISCONNECTED")setConnection("Reconectando");}};const onWillExpire=()=>void renew();const onDidExpire=()=>void renew(true);client.on("connection-state-change",onConnection);client.on("token-privilege-will-expire",onWillExpire);client.on("token-privilege-did-expire",onDidExpire);void (async()=>{try{await client.setClientRole("host");await client.join(agora.agoraAppId,agora.agoraChannel,agora.agoraToken,agora.agoraUid);onConnection("CONNECTED");}catch(cause){console.error("Agora broadcaster join error",cause);if(active){agoraReadyRef.current=false;setAgoraReady(false);setError("Não foi possível conectar ao servidor de transmissão.");}}})();return()=>{active=false;client.off("connection-state-change",onConnection);client.off("token-privilege-will-expire",onWillExpire);client.off("token-privilege-did-expire",onDidExpire);if(clientRef.current===client)clientRef.current=null;if(publishedClientRef.current===client)publishedClientRef.current=null;void client.leave().catch(cause=>console.error("Agora broadcaster leave error",cause));};},[agora?.agoraAppId,agora?.agoraChannel,agora?.agoraUid,roomId]);
  useEffect(()=>{const socket=connectSocket();const useAck=(ack:RoomAck,token?:string)=>{if(ack.ok&&ack.roomId&&ack.agoraAppId&&ack.agoraChannel&&ack.agoraUid!==undefined&&ack.agoraToken){const next:AgoraCredentials={agoraAppId:ack.agoraAppId,agoraChannel:ack.agoraChannel,agoraUid:ack.agoraUid,agoraToken:ack.agoraToken},current=credentialsRef.current,same=current&&current.agoraAppId===next.agoraAppId&&current.agoraChannel===next.agoraChannel&&current.agoraUid===next.agoraUid,client=clientRef.current;credentialsRef.current=next;setRoomId(ack.roomId);setAgora(next);setViewers(ack.viewers||0);if(same&&client){if(client.connectionState==="DISCONNECTED")void client.join(next.agoraAppId,next.agoraChannel,next.agoraToken,next.agoraUid).catch(cause=>console.error("Agora socket reconnect join error",cause));else if(current.agoraToken!==next.agoraToken)void client.renewToken(next.agoraToken).catch(cause=>console.error("Agora socket reconnect token error",cause));}if(liveRef.current)socket.emit("broadcast-started",{roomId:ack.roomId});if(ack.broadcasterToken){tokenRef.current=ack.broadcasterToken;sessionStorage.setItem("lumacast-broadcaster",JSON.stringify({roomId:ack.roomId,token:ack.broadcasterToken}));}else if(token)tokenRef.current=token;}else setError(ack.error||"Não foi possível criar a sala.");};const newRoom=()=>socket.emit("create-room",(ack:RoomAck)=>useAck(ack));const create=()=>{setConnection("Conectado");const saved=sessionStorage.getItem("lumacast-broadcaster");if(!saved)return newRoom();const parsed=JSON.parse(saved) as {roomId:string;token:string};socket.emit("reclaim-room",parsed,(ack:RoomAck)=>{if(ack.ok)useAck(ack,parsed.token);else{sessionStorage.removeItem("lumacast-broadcaster");newRoom();}});};const count=({count}:{count:number})=>setViewers(count);socket.on("connect",create);socket.on("disconnect",()=>setConnection("Reconectando"));socket.on("viewer-count",count);if(socket.connected)create();return()=>{socket.off("connect",create);socket.off("disconnect");socket.off("viewer-count",count);};},[]);
  const endCapture=useCallback((stream?:MediaStream)=>{if(stream&&streamRef.current!==stream)return;const current=streamRef.current,tracks=localTracksRef.current,client=clientRef.current;streamRef.current=null;localTracksRef.current=[];publishedClientRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setLive(false);setStats(null);setMuted(false);connectSocket().emit("broadcast-ended",{roomId});void (async()=>{try{if(client&&tracks.length)await client.unpublish(tracks);}catch(cause){console.error("Agora unpublish error",cause);}finally{tracks.forEach(track=>track.close());current?.getTracks().forEach(track=>track.stop());}})();},[roomId]);
  useEffect(()=>{if(!live)return;const timer=setInterval(async()=>{if(clientRef.current)setStats(await readAgoraStats(clientRef.current,streamRef.current));},1000);return()=>clearInterval(timer);},[live]);
  const stop=useCallback(()=>{void endCapture(streamRef.current||undefined);},[endCapture]);
  const start=async()=>{setError("");const client=clientRef.current;if(!client||!agoraReadyRef.current||client.connectionState!=="CONNECTED"){setError("Não foi possível conectar ao servidor de transmissão.");return;}let stream:MediaStream;try{stream=await navigator.mediaDevices.getDisplayMedia(displayConstraints(quality,fps));}catch(cause){console.error("Screen capture error",cause);setError((cause as DOMException).name==="NotAllowedError"?"O compartilhamento foi cancelado.":"Não foi possível capturar a tela. Verifique as permissões do navegador.");return;}const videoTrack=stream.getVideoTracks().find(activeTrack);if(!videoTrack){console.error("Screen capture error",new Error("A captura não forneceu vídeo ativo."));stream.getTracks().forEach(track=>track.stop());setError("Não foi possível capturar a tela. Verifique as permissões do navegador.");return;}const settings=videoTrack.getSettings(),bitrateMax=quality==="1080p"?(fps===60?5000:3000):quality==="720p"?(fps===60?3000:2000):(fps===60?3500:2500),videoAgoraTrack=AgoraRTC.createCustomVideoTrack({mediaStreamTrack:videoTrack,width:settings.width,height:settings.height,frameRate:fps,bitrateMax,optimizationMode:"motion"}),tracks:LocalAgoraTrack[]=[videoAgoraTrack],audioTrack=stream.getAudioTracks().find(activeTrack);if(audioTrack)tracks.push(AgoraRTC.createCustomAudioTrack({mediaStreamTrack:audioTrack,encoderConfig:"music_standard"}));console.info("LumaCast capture", {video:settings,requestedFps:fps,bitrateMax,hasAudio:!!audioTrack});streamRef.current=stream;localTracksRef.current=tracks;if(videoRef.current)videoRef.current.srcObject=stream;try{await client.publish(tracks);publishedClientRef.current=client;}catch(cause){console.error("Agora screen publish error",cause);tracks.forEach(track=>track.close());stream.getTracks().forEach(track=>track.stop());localTracksRef.current=[];if(streamRef.current===stream)streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setError("Não foi possível publicar a tela no servidor de transmissão.");return;}videoTrack.addEventListener("ended",()=>void endCapture(stream),{once:true});setLive(true);connectSocket().emit("broadcast-started",{roomId});};
  const toggleMute=()=>{const audioTracks=localTracksRef.current.filter((track):track is ILocalAudioTrack=>track.trackMediaType==="audio"),sourceTracks=streamRef.current?.getAudioTracks().filter(activeTrack)||[];if(!audioTracks.length||!sourceTracks.length){setError("Esta captura não possui áudio para silenciar.");return;}const nextMuted=!muted;try{sourceTracks.forEach(track=>{track.enabled=!nextMuted;});audioTracks.forEach(track=>track.setVolume(nextMuted?0:100));console.info("LumaCast audio mute",{muted:nextMuted,sourceEnabled:sourceTracks.map(track=>track.enabled),agoraVolume:nextMuted?0:100});setMuted(nextMuted);}catch(cause){console.error("Agora audio mute error",cause);setError("Não foi possível alterar o áudio da transmissão.");}};
  return <main className="studio-shell"><header className="studio-nav"><Logo/><div className="room-head"><span>SALA</span><b>{roomId||"CRIANDO…"}</b></div><div className="nav-status"><StatusPill label={live?"AO VIVO":"PRONTO"} tone={live?"live":"neutral"}/><span className="viewer-count"><Users/>{viewers}</span></div></header>
    <section className="studio-main"><div className="studio-stage"><div className={`broadcast-screen ${live?"has-video":""}`}><video ref={videoRef} autoPlay playsInline muted/><div className="stage-placeholder"><span><MonitorUp/></span><h2>Sua tela aparecerá aqui</h2><p>Escolha a qualidade e inicie quando estiver pronto.</p></div>{live&&<div className="live-corner"><i/>AO VIVO</div>}</div>
      <div className="control-dock"><button className={muted?"control danger":"control"} onClick={toggleMute} disabled={!live}>{muted?<MicOff/>:<Mic/>}<span>{muted?"Ativar áudio":"Silenciar"}</span></button>{!live?<button className="go-live" onClick={start} disabled={!roomId||!agora||!agoraReady}><Radio/>Iniciar transmissão</button>:<button className="stop-live" onClick={stop}><Square/>Parar transmissão</button>}<button className={`control ${showStats?"active":""}`} onClick={()=>setShowStats(!showStats)}><BarChart3/><span>Estatísticas</span></button></div>
    </div>
    <aside className="studio-side"><div className="side-card invite-card"><div className="card-title"><span><Eye/></span><div><b>Convide espectadores</b><small>Compartilhe este link</small></div></div><div className="share-code"><span>{roomId||"—"}</span><button onClick={async()=>{await navigator.clipboard.writeText(roomUrl);setCopied(true);setTimeout(()=>setCopied(false),1800);}}>{copied?<Check/>:<Clipboard/>}</button></div><p>O código também pode ser digitado na página inicial.</p></div>
      <div className="side-card settings-card"><div className="card-title"><span><Radio/></span><div><b>Qualidade</b><small>Defina antes de iniciar</small></div></div><label>RESOLUÇÃO<div className="select-wrap"><select value={quality} onChange={e=>setQuality(e.target.value as Quality)} disabled={live}><option value="auto">Automática</option><option value="720p">720p HD</option><option value="1080p">1080p Full HD</option></select><ChevronDown/></div></label><label>QUADROS POR SEGUNDO<div className="segmented"><button className={fps===30?"active":""} onClick={()=>setFps(30)} disabled={live}>30 FPS</button><button className={fps===60?"active":""} onClick={()=>setFps(60)} disabled={live}>60 FPS</button></div></label></div>
      <div className="connection-card"><span><i className={connection==="Conectado"?"ok":""}/><b>{connection}</b></span><small>{connection==="Conectado"?"Servidor de sinalização online":"Tentando restabelecer…"}</small></div>
    </aside></section>
    {showStats&&<section className="stats-drawer"><h3>Estatísticas da conexão</h3><StatsPanel stats={stats}/></section>}{error&&<div className="toast-error"><WifiOff/>{error}<button onClick={()=>setError("")}>×</button></div>}
  </main>;
}
