import Daily,{type DailyCall} from "@daily-co/daily-js";
import { BarChart3, Check, ChevronDown, Clipboard, Eye, Mic, MicOff, MonitorUp, Radio, Square, Users, WifiOff } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { Logo } from "../components/Logo";
import { StatsPanel } from "../components/StatsPanel";
import { StatusPill } from "../components/StatusPill";
import { connectSocket } from "../services/socket";
import { displayConstraints,readDailyStats } from "../services/webrtc";
import type { FrameRate,Quality,RoomAck,StreamStats } from "../types";

type DailyCredentials={url:string;token:string};
const activeTrack=(track:MediaStreamTrack|undefined)=>!!track&&track.readyState!=="ended";
export function BroadcasterPage(){
  const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),callRef=useRef<DailyCall|null>(null),joinRef=useRef<Promise<unknown>|null>(null),tokenRef=useRef(""),liveRef=useRef(false),dailyReadyRef=useRef(false),publishedCallRef=useRef<DailyCall|null>(null);
  const [roomId,setRoomId]=useState(""),[daily,setDaily]=useState<DailyCredentials|null>(null),[viewers,setViewers]=useState(0),[quality,setQuality]=useState<Quality>("1080p"),[fps,setFps]=useState<FrameRate>(30),[live,setLive]=useState(false),[dailyReady,setDailyReady]=useState(false),[muted,setMuted]=useState(false),[copied,setCopied]=useState(false),[connection,setConnection]=useState("Conectando"),[error,setError]=useState(""),[stats,setStats]=useState<StreamStats|null>(null),[showStats,setShowStats]=useState(false);
  const roomUrl=roomId?`${location.origin}/watch/${roomId}`:"";
  useEffect(()=>{liveRef.current=live;},[live]);
  useEffect(()=>{if(!daily)return;let active=true;dailyReadyRef.current=false;setDailyReady(false);const call=Daily.createCallObject({audioSource:false,videoSource:false});callRef.current=call;const onError=(event:unknown)=>{console.error("Daily call error",event);dailyReadyRef.current=false;setDailyReady(false);setError("Não foi possível conectar ao servidor de transmissão.");};const republish=()=>{const stream=streamRef.current,videoTrack=stream?.getVideoTracks().find(activeTrack);if(!active||!liveRef.current||!stream||!videoTrack||publishedCallRef.current===call)return;try{call.startScreenShare({mediaStream:stream});publishedCallRef.current=call;}catch(cause){console.error("Daily screen republish error",cause);setError("A transmissão continua ativa, mas não foi possível republicar sua tela após a reconexão.");}};const onJoined=()=>{if(!active||dailyReadyRef.current)return;dailyReadyRef.current=true;setDailyReady(true);console.info("Daily local participant permissions",call.participants().local?.permissions);republish();};const onLeft=()=>{if(!active)return;dailyReadyRef.current=false;setDailyReady(false);};call.on("joined-meeting",onJoined);call.on("left-meeting",onLeft);call.on("error",onError);joinRef.current=call.join({url:daily.url,token:daily.token,audioSource:false,videoSource:false}).then(onJoined).catch(cause=>{console.error("Daily join error",cause);dailyReadyRef.current=false;setDailyReady(false);setError("Não foi possível conectar ao servidor de transmissão.");throw cause;});return()=>{active=false;call.off("joined-meeting",onJoined);call.off("left-meeting",onLeft);call.off("error",onError);if(callRef.current===call){callRef.current=null;joinRef.current=null;}if(publishedCallRef.current===call)publishedCallRef.current=null;void call.destroy();};},[daily]);
  useEffect(()=>{const socket=connectSocket();const useAck=(ack:RoomAck,token?:string)=>{if(ack.ok&&ack.roomId&&ack.dailyUrl&&ack.dailyToken){setRoomId(ack.roomId);setDaily({url:ack.dailyUrl,token:ack.dailyToken});setViewers(ack.viewers||0);if(ack.broadcasterToken){tokenRef.current=ack.broadcasterToken;sessionStorage.setItem("lumacast-broadcaster",JSON.stringify({roomId:ack.roomId,token:ack.broadcasterToken}));}else if(token)tokenRef.current=token;}else setError(ack.error||"Não foi possível criar a sala.");};const newRoom=()=>socket.emit("create-room",(ack:RoomAck)=>useAck(ack));const create=()=>{setConnection("Conectado");const saved=sessionStorage.getItem("lumacast-broadcaster");if(!saved)return newRoom();const parsed=JSON.parse(saved) as {roomId:string;token:string};socket.emit("reclaim-room",parsed,(ack:RoomAck)=>{if(ack.ok)useAck(ack,parsed.token);else{sessionStorage.removeItem("lumacast-broadcaster");newRoom();}});};const count=({count}:{count:number})=>setViewers(count);socket.on("connect",create);socket.on("disconnect",()=>setConnection("Reconectando"));socket.on("viewer-count",count);if(socket.connected)create();return()=>{socket.off("connect",create);socket.off("disconnect");socket.off("viewer-count",count);};},[]);
  const endCapture=useCallback((stream?:MediaStream)=>{if(stream&&streamRef.current!==stream)return;streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;callRef.current?.stopScreenShare();publishedCallRef.current=null;connectSocket().emit("broadcast-ended",{roomId});setLive(false);setStats(null);setMuted(false);},[roomId]);
  useEffect(()=>{if(!live)return;const timer=setInterval(async()=>{if(callRef.current)setStats(await readDailyStats(callRef.current,streamRef.current));},1000);return()=>clearInterval(timer);},[live]);
  const stop=useCallback(()=>{const stream=streamRef.current;if(stream){stream.getTracks().forEach(track=>track.stop());endCapture(stream);}else endCapture();},[endCapture]);
  const start=async()=>{setError("");const call=callRef.current;console.info("Daily meeting state before start",call?.meetingState());if(!call||!dailyReadyRef.current||call.meetingState()!=="joined-meeting"){setError("Não foi possível conectar ao servidor de transmissão.");return;}let stream:MediaStream;try{stream=await navigator.mediaDevices.getDisplayMedia(displayConstraints(quality,fps));}catch(cause){console.error("Screen capture error",cause);setError((cause as DOMException).name==="NotAllowedError"?"O compartilhamento foi cancelado.":"Não foi possível capturar a tela. Verifique as permissões do navegador.");return;}const videoTrack=stream.getVideoTracks().find(activeTrack);if(!videoTrack){console.error("Screen capture error",new Error("A captura não forneceu vídeo ativo."));stream.getTracks().forEach(track=>track.stop());setError("Não foi possível capturar a tela. Verifique as permissões do navegador.");return;}streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;try{call.startScreenShare({mediaStream:stream});publishedCallRef.current=call;}catch(cause){console.error("Daily screen publish error",cause);stream.getTracks().forEach(track=>track.stop());if(streamRef.current===stream)streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setError("Não foi possível publicar a tela no servidor de transmissão.");return;}videoTrack.addEventListener("ended",()=>endCapture(stream),{once:true});setLive(true);connectSocket().emit("broadcast-started",{roomId});};
  const toggleMute=()=>{const tracks=streamRef.current?.getAudioTracks().filter(activeTrack)||[];tracks.forEach(track=>track.enabled=muted);setMuted(!muted);};
  return <main className="studio-shell"><header className="studio-nav"><Logo/><div className="room-head"><span>SALA</span><b>{roomId||"CRIANDO…"}</b></div><div className="nav-status"><StatusPill label={live?"AO VIVO":"PRONTO"} tone={live?"live":"neutral"}/><span className="viewer-count"><Users/>{viewers}</span></div></header>
    <section className="studio-main"><div className="studio-stage"><div className={`broadcast-screen ${live?"has-video":""}`}><video ref={videoRef} autoPlay playsInline muted/><div className="stage-placeholder"><span><MonitorUp/></span><h2>Sua tela aparecerá aqui</h2><p>Escolha a qualidade e inicie quando estiver pronto.</p></div>{live&&<div className="live-corner"><i/>AO VIVO</div>}</div>
      <div className="control-dock"><button className={muted?"control danger":"control"} onClick={toggleMute} disabled={!live}>{muted?<MicOff/>:<Mic/>}<span>{muted?"Ativar áudio":"Silenciar"}</span></button>{!live?<button className="go-live" onClick={start} disabled={!roomId||!daily||!dailyReady}><Radio/>Iniciar transmissão</button>:<button className="stop-live" onClick={stop}><Square/>Parar transmissão</button>}<button className={`control ${showStats?"active":""}`} onClick={()=>setShowStats(!showStats)}><BarChart3/><span>Estatísticas</span></button></div>
    </div>
    <aside className="studio-side"><div className="side-card invite-card"><div className="card-title"><span><Eye/></span><div><b>Convide espectadores</b><small>Compartilhe este link</small></div></div><div className="share-code"><span>{roomId||"—"}</span><button onClick={async()=>{await navigator.clipboard.writeText(roomUrl);setCopied(true);setTimeout(()=>setCopied(false),1800);}}>{copied?<Check/>:<Clipboard/>}</button></div><p>O código também pode ser digitado na página inicial.</p></div>
      <div className="side-card settings-card"><div className="card-title"><span><Radio/></span><div><b>Qualidade</b><small>Defina antes de iniciar</small></div></div><label>RESOLUÇÃO<div className="select-wrap"><select value={quality} onChange={e=>setQuality(e.target.value as Quality)} disabled={live}><option value="auto">Automática</option><option value="720p">720p HD</option><option value="1080p">1080p Full HD</option></select><ChevronDown/></div></label><label>QUADROS POR SEGUNDO<div className="segmented"><button className={fps===30?"active":""} onClick={()=>setFps(30)} disabled={live}>30 FPS</button><button className={fps===60?"active":""} onClick={()=>setFps(60)} disabled={live}>60 FPS</button></div></label></div>
      <div className="connection-card"><span><i className={connection==="Conectado"?"ok":""}/><b>{connection}</b></span><small>{connection==="Conectado"?"Servidor de sinalização online":"Tentando restabelecer…"}</small></div>
    </aside></section>
    {showStats&&<section className="stats-drawer"><h3>Estatísticas da conexão</h3><StatsPanel stats={stats}/></section>}{error&&<div className="toast-error"><WifiOff/>{error}<button onClick={()=>setError("")}>×</button></div>}
  </main>;
}
