import { BarChart3, Check, ChevronDown, Clipboard, Eye, Mic, MicOff, MonitorUp, Radio, Square, Users, WifiOff } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { Logo } from "../components/Logo";
import { StatsPanel } from "../components/StatsPanel";
import { StatusPill } from "../components/StatusPill";
import { connectSocket } from "../services/socket";
import { displayConstraints, getIceServers, readStats, tuneSender } from "../services/webrtc";
import type { FrameRate, IcePayload, Quality, RoomAck, SessionPayload, StreamStats } from "../types";

const unhealthy=(pc:RTCPeerConnection)=>["failed","closed"].includes(pc.connectionState);
const valid=(track:MediaStreamTrack|undefined)=>!!track&&track.readyState!=="ended";
const report=(viewerId:string,pc:RTCPeerConnection,error:unknown)=>console.error("WebRTC negotiation error",{viewerId,signalingState:pc.signalingState,connectionState:pc.connectionState,iceConnectionState:pc.iceConnectionState,error});

export function BroadcasterPage(){
  const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),peers=useRef(new Map<string,RTCPeerConnection>()),pendingIce=useRef(new Map<string,RTCIceCandidateInit[]>()),sessionIds=useRef(new Map<string,string>()),negotiations=useRef(new Map<string,Promise<void>>()),rerunOffer=useRef(new Set<string>()),viewerIds=useRef(new Set<string>()),tokenRef=useRef("");
  const [roomId,setRoomId]=useState(""),[viewers,setViewers]=useState(0),[quality,setQuality]=useState<Quality>("1080p"),[fps,setFps]=useState<FrameRate>(30),[live,setLive]=useState(false),[muted,setMuted]=useState(false),[copied,setCopied]=useState(false),[connection,setConnection]=useState("Conectando"),[error,setError]=useState(""),[stats,setStats]=useState<StreamStats|null>(null),[showStats,setShowStats]=useState(false);
  const roomUrl=roomId?`${location.origin}/watch/${roomId}`:"";
  const closePeer=useCallback((id:string)=>{peers.current.get(id)?.close();peers.current.delete(id);pendingIce.current.delete(id);sessionIds.current.delete(id);negotiations.current.delete(id);rerunOffer.current.delete(id);},[]);
  const makePeer=useCallback(async(viewerId:string)=>{closePeer(viewerId);const pc=new RTCPeerConnection({iceServers:await getIceServers()});peers.current.set(viewerId,pc);pc.onicecandidate=e=>{const sessionId=sessionIds.current.get(viewerId);if(e.candidate&&sessionId)connectSocket().emit("ice-candidate",{roomId,viewerId,sessionId,candidate:e.candidate.toJSON()});};pc.onconnectionstatechange=()=>{if(pc.connectionState==="disconnected")setTimeout(()=>{if(peers.current.get(viewerId)===pc&&pc.connectionState==="disconnected")console.warn("WebRTC peer remained disconnected",{viewerId});},5000);else if(unhealthy(pc)&&peers.current.get(viewerId)===pc)console.warn("WebRTC peer needs replacement",{viewerId,connectionState:pc.connectionState});};return pc;},[closePeer,roomId]);
  const syncTracks=useCallback(async(pc:RTCPeerConnection,stream:MediaStream)=>{let added=false;for(const kind of ["video","audio"] as const){const track=(kind==="video"?stream.getVideoTracks():stream.getAudioTracks()).find(valid);if(!track)continue;const sender=pc.getTransceivers().find(transceiver=>transceiver.receiver.track.kind===kind)?.sender||pc.getSenders().find(s=>s.track?.kind===kind);if(sender){if(sender.track!==track)await sender.replaceTrack(track);if(kind==="video")await tuneSender(sender,quality,fps);}else{const sender=pc.addTrack(track,stream);if(kind==="video")await tuneSender(sender,quality,fps);added=true;}}return added;},[fps,quality]);
  const offer=useCallback(async(viewerId:string,pc:RTCPeerConnection,iceRestart=false)=>{if(negotiations.current.has(viewerId)){rerunOffer.current.add(viewerId);return negotiations.current.get(viewerId)!;}const task=(async()=>{do{rerunOffer.current.delete(viewerId);if(peers.current.get(viewerId)!==pc||pc.signalingState!=="stable"||pc.connectionState==="closed")return;const sessionId=crypto.randomUUID();sessionIds.current.set(viewerId,sessionId);pendingIce.current.delete(viewerId);try{const description=await pc.createOffer({iceRestart});if(peers.current.get(viewerId)!==pc||sessionIds.current.get(viewerId)!==sessionId)return;await pc.setLocalDescription(description);connectSocket().emit("offer",{roomId,viewerId,sessionId,sdp:description});}catch(cause){report(viewerId,pc,cause);setError("Não foi possível concluir a conexão com um espectador.");return;}}while(rerunOffer.current.has(viewerId));})().finally(()=>negotiations.current.delete(viewerId));negotiations.current.set(viewerId,task);return task;},[roomId]);
  const connectViewer=useCallback(async(viewerId:string,forceOffer=false)=>{const stream=streamRef.current;if(!stream||!stream.getVideoTracks().some(valid))return;let pc=peers.current.get(viewerId);if(!pc||unhealthy(pc)){pc=await makePeer(viewerId);forceOffer=true;}try{const added=await syncTracks(pc,stream);if(forceOffer||added)await offer(viewerId,pc,forceOffer);}catch(cause){report(viewerId,pc,cause);closePeer(viewerId);setError("Não foi possível concluir a conexão com um espectador.");}},[closePeer,makePeer,offer,syncTracks]);
  const endCapture=useCallback((stream?:MediaStream)=>{if(stream&&streamRef.current!==stream)return;streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;for(const pc of peers.current.values())for(const sender of pc.getSenders())if(sender.track?.readyState==="ended")void sender.replaceTrack(null);connectSocket().emit("broadcast-ended",{roomId});setLive(false);setStats(null);setMuted(false);},[roomId]);
  useEffect(()=>{const socket=connectSocket();const newRoom=()=>socket.emit("create-room",(ack:RoomAck)=>{if(ack.ok&&ack.roomId&&ack.broadcasterToken){setRoomId(ack.roomId);tokenRef.current=ack.broadcasterToken;sessionStorage.setItem("lumacast-broadcaster",JSON.stringify({roomId:ack.roomId,token:ack.broadcasterToken}));}else setError(ack.error||"Não foi possível criar a sala.");});const create=()=>{setConnection("Conectado");const saved=sessionStorage.getItem("lumacast-broadcaster");if(!saved)return newRoom();const parsed=JSON.parse(saved) as {roomId:string;token:string};socket.emit("reclaim-room",parsed,(ack:RoomAck)=>{if(ack.ok&&ack.roomId){setRoomId(ack.roomId);tokenRef.current=parsed.token;setViewers(ack.viewers||0);}else{sessionStorage.removeItem("lumacast-broadcaster");newRoom();}});};const joined=({viewerId,count}:{viewerId:string;count:number})=>{viewerIds.current.add(viewerId);setViewers(count);if(streamRef.current)void connectViewer(viewerId,true);};const left=({viewerId,count}:{viewerId:string;count:number})=>{closePeer(viewerId);viewerIds.current.delete(viewerId);setViewers(count);};const answer=async({viewerId,sessionId,sdp}:SessionPayload)=>{const pc=peers.current.get(viewerId);if(!pc||sessionId!==sessionIds.current.get(viewerId)||pc.signalingState!=="have-local-offer")return;try{await pc.setRemoteDescription(sdp);for(const candidate of pendingIce.current.get(viewerId)||[])await pc.addIceCandidate(candidate);pendingIce.current.delete(viewerId);}catch(cause){report(viewerId,pc,cause);setError("Não foi possível concluir a conexão com um espectador.");}};const candidate=async({viewerId,sessionId,candidate:ice}:IcePayload)=>{const pc=peers.current.get(viewerId);if(!pc||sessionId!==sessionIds.current.get(viewerId))return;if(!pc.remoteDescription){const queued=pendingIce.current.get(viewerId)||[];queued.push(ice);pendingIce.current.set(viewerId,queued);return;}try{await pc.addIceCandidate(ice);}catch(cause){report(viewerId,pc,cause);}};socket.on("connect",create);socket.on("disconnect",()=>setConnection("Reconectando"));socket.on("viewer-joined",joined);socket.on("viewer-left",left);socket.on("answer",answer);socket.on("ice-candidate",candidate);if(socket.connected)create();return()=>{socket.off("connect",create);socket.off("disconnect");socket.off("viewer-joined",joined);socket.off("viewer-left",left);socket.off("answer",answer);socket.off("ice-candidate",candidate);};},[closePeer,connectViewer]);
  useEffect(()=>{if(!live)return;const timer=setInterval(async()=>{const pc=peers.current.values().next().value as RTCPeerConnection|undefined;if(pc)setStats(await readStats(pc));},1000);return()=>clearInterval(timer);},[live]);
  const stop=useCallback(()=>{const stream=streamRef.current;if(stream){stream.getTracks().forEach(track=>track.stop());endCapture(stream);}else endCapture();},[endCapture]);
  const start=async()=>{setError("");try{const stream=await navigator.mediaDevices.getDisplayMedia(displayConstraints(quality,fps)),videoTrack=stream.getVideoTracks().find(valid);if(!videoTrack)throw new Error("A captura não forneceu vídeo ativo.");streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;videoTrack.addEventListener("ended",()=>endCapture(stream),{once:true});setLive(true);connectSocket().emit("broadcast-started",{roomId});for(const viewerId of viewerIds.current)await connectViewer(viewerId);}catch(cause){console.error("Screen capture error",cause);setError((cause as DOMException).name==="NotAllowedError"?"O compartilhamento foi cancelado. Sua tela não foi transmitida.":"Não foi possível iniciar a captura. Verifique as permissões do navegador.");}};
  const toggleMute=()=>{const tracks=streamRef.current?.getAudioTracks().filter(valid)||[];tracks.forEach(t=>t.enabled=muted);setMuted(!muted);};
  return <main className="studio-shell"><header className="studio-nav"><Logo/><div className="room-head"><span>SALA</span><b>{roomId||"CRIANDO…"}</b></div><div className="nav-status"><StatusPill label={live?"AO VIVO":"PRONTO"} tone={live?"live":"neutral"}/><span className="viewer-count"><Users/>{viewers}</span></div></header><section className="studio-main"><div className="studio-stage"><div className={`broadcast-screen ${live?"has-video":""}`}><video ref={videoRef} autoPlay playsInline muted/><div className="stage-placeholder"><span><MonitorUp/></span><h2>Sua tela aparecerá aqui</h2><p>Escolha a qualidade e inicie quando estiver pronto.</p></div>{live&&<div className="live-corner"><i/>AO VIVO</div>}</div><div className="control-dock"><button className={muted?"control danger":"control"} onClick={toggleMute} disabled={!live}>{muted?<MicOff/>:<Mic/>}<span>{muted?"Ativar áudio":"Silenciar"}</span></button>{!live?<button className="go-live" onClick={start} disabled={!roomId}><Radio/>Iniciar transmissão</button>:<button className="stop-live" onClick={stop}><Square/>Parar transmissão</button>}<button className={`control ${showStats?"active":""}`} onClick={()=>setShowStats(!showStats)}><BarChart3/><span>Estatísticas</span></button></div></div><aside className="studio-side"><div className="side-card invite-card"><div className="card-title"><span><Eye/></span><div><b>Convide espectadores</b><small>Compartilhe este link</small></div></div><div className="share-code"><span>{roomId||"—"}</span><button onClick={async()=>{await navigator.clipboard.writeText(roomUrl);setCopied(true);setTimeout(()=>setCopied(false),1800);}}>{copied?<Check/>:<Clipboard/>}</button></div><p>O código também pode ser digitado na página inicial.</p></div><div className="side-card settings-card"><div className="card-title"><span><Radio/></span><div><b>Qualidade</b><small>Defina antes de iniciar</small></div></div><label>RESOLUÇÃO<div className="select-wrap"><select value={quality} onChange={e=>setQuality(e.target.value as Quality)} disabled={live}><option value="auto">Automática</option><option value="720p">720p HD</option><option value="1080p">1080p Full HD</option></select><ChevronDown/></div></label><label>QUADROS POR SEGUNDO<div className="segmented"><button className={fps===30?"active":""} onClick={()=>setFps(30)} disabled={live}>30 FPS</button><button className={fps===60?"active":""} onClick={()=>setFps(60)} disabled={live}>60 FPS</button></div></label></div><div className="connection-card"><span><i className={connection==="Conectado"?"ok":""}/><b>{connection}</b></span><small>{connection==="Conectado"?"Servidor de sinalização online":"Tentando restabelecer…"}</small></div></aside></section>{showStats&&<section className="stats-drawer"><h3>Estatísticas da conexão</h3><StatsPanel stats={stats}/></section>}{error&&<div className="toast-error"><WifiOff/>{error}<button onClick={()=>setError("")}>×</button></div>}</main>;
}
