import Daily,{type DailyCall,type DailyParticipant} from "@daily-co/daily-js";
import { BarChart3, LoaderCircle, Radio, RefreshCw, Signal, Users } from "lucide-react";
import { useEffect,useRef,useState } from "react";
import { Logo } from "../components/Logo";
import { StatsPanel } from "../components/StatsPanel";
import { StatusPill } from "../components/StatusPill";
import { VideoStage } from "../components/VideoStage";
import { connectSocket } from "../services/socket";
import { readDailyStats } from "../services/webrtc";
import type { JoinAck,StreamStats } from "../types";

type DailyCredentials={url:string;token:string};
type ViewerStatus="joining"|"waiting"|"live"|"ended"|"missing"|"reconnecting";
export function ViewerPage({roomId}:{roomId:string}){
  const videoRef=useRef<HTMLVideoElement>(null),callRef=useRef<DailyCall|null>(null),remoteStream=useRef<MediaStream|null>(null),roomLive=useRef(false);
  const [daily,setDaily]=useState<DailyCredentials|null>(null),[status,setStatus]=useState<ViewerStatus>("joining"),[stats,setStats]=useState<StreamStats|null>(null),[showStats,setShowStats]=useState(false),[viewerCount,setViewerCount]=useState(1);
  useEffect(()=>{const socket=connectSocket();const join=()=>{setStatus(current=>current==="live"?"reconnecting":"joining");socket.emit("join-room",{roomId},(ack:JoinAck)=>{if(!ack.ok||!ack.dailyUrl||!ack.dailyToken){setStatus("missing");return;}roomLive.current=!!ack.live;setStatus(ack.live?"joining":"waiting");setDaily({url:ack.dailyUrl,token:ack.dailyToken});});};const state=({live,count}:{live:boolean;count:number})=>{roomLive.current=live;setViewerCount(count);if(!live){remoteStream.current=null;if(videoRef.current)videoRef.current.srcObject=null;setStatus("waiting");}};socket.on("connect",join);socket.on("disconnect",()=>setStatus("reconnecting"));socket.on("room-state",state);socket.on("broadcast-started",()=>{roomLive.current=true;setStatus("joining");});socket.on("broadcast-ended",()=>{roomLive.current=false;remoteStream.current=null;if(videoRef.current)videoRef.current.srcObject=null;setStatus("waiting");});socket.on("broadcaster-disconnected",()=>setStatus("reconnecting"));if(socket.connected)join();return()=>{socket.emit("leave-room",{roomId});socket.off("connect",join);socket.off("disconnect");socket.off("room-state",state);socket.off("broadcast-started");socket.off("broadcast-ended");socket.off("broadcaster-disconnected");};},[roomId]);
  useEffect(()=>{if(!daily)return;let active=true;const call=Daily.createCallObject({audioSource:false,videoSource:false});callRef.current=call;const sync=()=>{if(!active)return;const participant=(Object.values(call.participants()) as DailyParticipant[]).find(item=>!item.local&&item.tracks.screenVideo.persistentTrack?.readyState==="live"),video=participant?.tracks.screenVideo.persistentTrack,audio=participant?.tracks.screenAudio.persistentTrack;if(video){const tracks=[video,...(audio?.readyState==="live"?[audio]:[])],current=remoteStream.current;if(!current||current.getTracks().map(track=>track.id).join()!==tracks.map(track=>track.id).join()){remoteStream.current=new MediaStream(tracks);if(videoRef.current){videoRef.current.srcObject=remoteStream.current;void videoRef.current.play().catch(()=>undefined);}}setStatus("live");}else if(roomLive.current)setStatus("joining");};const onError=(event:unknown)=>{console.error("Daily viewer error",event);if(active)setStatus("reconnecting");};const onLeft=()=>{if(active)setStatus("reconnecting");};call.on("participant-joined",sync);call.on("participant-updated",sync);call.on("participant-left",sync);call.on("track-started",sync);call.on("track-stopped",sync);call.on("error",onError);call.on("left-meeting",onLeft);void call.join({url:daily.url,token:daily.token,audioSource:false,videoSource:false}).then(sync).catch(onError);return()=>{active=false;call.off("participant-joined",sync);call.off("participant-updated",sync);call.off("participant-left",sync);call.off("track-started",sync);call.off("track-stopped",sync);call.off("error",onError);call.off("left-meeting",onLeft);if(callRef.current===call)callRef.current=null;void call.destroy();};},[daily]);
  useEffect(()=>{if(status!=="live")return;const timer=setInterval(async()=>{if(callRef.current)setStats(await readDailyStats(callRef.current,remoteStream.current));},1000);return()=>clearInterval(timer);},[status]);
  const copy={joining:["Conectando à transmissão","Conectando à distribuição segura de vídeo."],waiting:["O transmissor ainda não começou","Você está na sala certa. A transmissão iniciará automaticamente."],ended:["A transmissão foi encerrada","Você pode aguardar aqui caso o transmissor volte."],missing:["Sala não encontrada","Confira o código ou peça um novo link ao transmissor."],reconnecting:["Reconectando…","A conexão caiu. Estamos tentando restabelecer automaticamente."],live:["",""]}[status];
  return <main className="viewer-shell"><header className="viewer-nav"><Logo/><div className="viewer-room"><span>SALA</span><b>{roomId}</b></div><div className="viewer-nav-actions"><StatusPill label={status==="live"?"AO VIVO":status==="reconnecting"?"RECONECTANDO":"AGUARDANDO"} tone={status==="live"?"live":status==="reconnecting"?"warn":"neutral"}/><span><Users/>{viewerCount}</span></div></header>
    <section className="watch-area"><div className="watch-heading"><div><span className="mini-label"><Radio/>TRANSMISSÃO</span><h1>Tela compartilhada</h1></div><button onClick={()=>setShowStats(!showStats)} className={showStats?"active":""}><BarChart3/> Estatísticas</button></div><VideoStage videoRef={videoRef} active={status==="live"} emptyTitle={copy[0]} emptyText={copy[1]}/>{status==="reconnecting"&&<div className="reconnect-line"><LoaderCircle/> Tentando reconectar</div>}{status==="missing"&&<button className="back-home" onClick={()=>location.assign("/")}><RefreshCw/> Digitar outro código</button>}</section>
    <footer className="viewer-foot"><span><Signal/> Conexão WebRTC via SFU</span><span>O conteúdo não é gravado pelo LumaCast</span></footer>{showStats&&<section className="stats-drawer viewer-stats"><h3>Estatísticas da transmissão</h3><StatsPanel stats={stats}/></section>}
  </main>;
}
