import { BarChart3,LoaderCircle,Radio,RefreshCw,Signal,Square,Users,Video,VideoOff,Volume2,VolumeX } from "lucide-react";
import { useState } from "react";
import { Logo } from "../components/Logo";
import { NameDialog } from "../components/NameDialog";
import { CameraDock,ParticipantsSidebar } from "../components/ParticipantsSidebar";
import { StatsPanel } from "../components/StatsPanel";
import { StatusPill } from "../components/StatusPill";
import { VideoStage } from "../components/VideoStage";
import { useMediaPreferences } from "../hooks/useMediaPreferences";
import { useCollaborativeRoom } from "../services/useCollaborativeRoom";
import type { CameraPreset,Quality } from "../types";

export function ViewerPage({roomId}:{roomId:string}){
  const room=useCollaborativeRoom(false,roomId),[showStats,setShowStats]=useState(false),{quality,setQuality,fps,setFps}=useMediaPreferences(),canShare=typeof navigator.mediaDevices?.getDisplayMedia==="function",needsName=!sessionStorage.getItem("lumacast-display-name");
  const live=room.roomState.live,screenStarting=!!room.roomState.activeScreenSharerId&&!live,busy=!!room.roomState.activeScreenSharerId&&!room.ownsScreenLock,missing=room.status==="missing",reconnecting=room.status==="Reconectando",emptyTitle=room.switching?"Trocando servidor de transmissão…":screenStarting?(room.ownsScreenLock?"Preparando sua transmissão…":(room.roomState.activeScreenSharerName||"Alguém")+" está iniciando uma transmissão…"):live?"Conectando à transmissão":"Nenhuma tela sendo compartilhada",emptyText=screenStarting?(room.ownsScreenLock?"Escolha a tela ou janela que deseja compartilhar.":"Aguarde enquanto a tela é preparada."):live?"Conectando à distribuição segura de vídeo.":"Você está na sala certa. Qualquer participante pode começar.";
  return <main className="viewer-shell viewer-compact"><header className="viewer-nav"><Logo/><div className="viewer-room"><span>SALA</span><b>{roomId}</b></div><div className="viewer-nav-actions"><StatusPill label={live?"AO VIVO":reconnecting?"RECONECTANDO":"AGUARDANDO"} tone={live?"live":reconnecting?"warn":"neutral"}/><span aria-label={`${room.roomState.count+1} participantes`}><Users/>{room.roomState.count+1}</span></div></header>
    <section className="watch-area collaborative-layout viewer-compact-layout"><div className="watch-main"><div className="watch-heading"><div><span className="mini-label"><Radio/>TRANSMISSÃO</span><h1>Tela compartilhada</h1></div><button type="button" aria-pressed={showStats} onClick={()=>setShowStats(!showStats)} className={showStats?"active":""}><BarChart3/> Estatísticas</button></div><VideoStage videoRef={room.videoRef} active={live&&!room.switching} muted={room.isScreenSharer} emptyTitle={emptyTitle} emptyText={emptyText}/><CameraDock cameras={room.cameras} participants={room.roomState.participants}/>{reconnecting&&<div className="reconnect-line" role="status"><LoaderCircle/> Tentando reconectar</div>}{missing&&<button type="button" className="back-home" onClick={()=>location.assign("/")}><RefreshCw/> Digitar outro código</button>}
      <div className="control-dock collaborative-controls"><button type="button" className="control" onClick={()=>void room.toggleCamera()}>{room.cameraOn?<Video/>:<VideoOff/>}<span>Câmera</span></button>{room.isScreenSharer?<button type="button" className="stop-live" onClick={()=>void room.stopScreen()}><Square/>Parar transmissão</button>:<button type="button" className="go-live" onClick={()=>void room.startScreen(quality,fps)} disabled={busy||missing||!canShare} title={!canShare?"Compartilhamento de tela não é suportado neste navegador.":undefined}>{!canShare?"Tela indisponível":busy?"Tela ocupada":"Compartilhar minha tela"}</button>}{room.isScreenSharer&&<button type="button" className="control" onClick={()=>void room.toggleScreenAudio()}>{room.muted?<VolumeX/>:<Volume2/>}<span>{room.muted?"Ativar áudio da tela":"Silenciar áudio da tela"}</span></button>}</div><div className="viewer-share-options"><select aria-label="Qualidade da câmera" value={room.cameraPreset} onChange={e=>room.setCameraPreset(e.target.value as CameraPreset)} disabled={room.cameraOn}><option value="720p40">Câmera 720p · 40 FPS</option><option value="480p60">Câmera 480p · 60 FPS</option></select><select aria-label="Resolução da tela" value={quality} onChange={e=>{const next=e.target.value as Quality;setQuality(next);if(room.isScreenSharer)void room.updateScreenQuality(next);}}><option value="auto">Automática</option><option value="720p">720p HD</option><option value="1080p">1080p Full HD</option></select><button type="button" aria-pressed={fps===30} onClick={()=>{setFps(30);if(room.isScreenSharer)void room.updateScreenFrameRate(30);}} className={fps===30?"active":""}>30 FPS</button><button type="button" aria-pressed={fps===60} onClick={()=>{setFps(60);if(room.isScreenSharer)void room.updateScreenFrameRate(60);}} className={fps===60?"active":""}>60 FPS</button></div></div><ParticipantsSidebar participants={room.roomState.participants}/></section>
    <footer className="viewer-foot"><span><Signal/> Conexão WebRTC via SFU</span><span>O conteúdo não é gravado pelo LumaCast</span></footer>
    {showStats&&<section className="stats-drawer viewer-stats" aria-live="polite"><h3>Estatísticas da transmissão</h3><StatsPanel stats={room.stats}/></section>}
    {room.error&&<div className="toast-error" role="alert">{room.error}<button type="button" aria-label="Fechar aviso" onClick={()=>room.setError("")}>×</button></div>}
    {needsName&&<NameDialog eyebrow={`Entrar na sala ${roomId}`} submitLabel="Entrar" onSubmit={value=>{sessionStorage.setItem("lumacast-display-name",value);location.reload();}} onCancel={()=>location.assign("/")}/>}
  </main>;
}
