[package]
name = "lunira-screen-desktop"
version = "0.1.9"
description = "Lunira Screen desktop client"
authors = ["Lunira Screen"]
edition = "2021"

[lib]
name = "lunira_screen_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
