import type { Server, Socket } from "socket.io";
import { createDailyRoom, createDailyToken, deleteDailyRoom } from "./daily.js";
import { RoomStore, validRoomId } from "./rooms.js";

type Ack=(payload:{ok:boolean;roomId?:string;broadcasterToken?:string;dailyUrl?:string;dailyToken?:string;error?:string;live?:boolean;viewers?:number})=>void;
const safeAck=(ack:unknown,payload:Parameters<Ack>[0])=>{if(typeof ack==="function")(ack as Ack)(payload);};
const limiter=new Map<string,{start:number;count:number}>();
function allowed(socket:Socket,limit=140,windowMs=10_000){const now=Date.now(),key=socket.handshake.address;let state=limiter.get(key);if(!state||now-state.start>windowMs)state={start:now,count:0};state.count++;limiter.set(key,state);return state.count<=limit;}

export function registerSignaling(io:Server){const rooms=new RoomStore();
  io.on("connection",socket=>{
    socket.on("create-room",async(ack:Ack)=>{const existing=rooms.findByBroadcaster(socket.id);if(existing){try{return safeAck(ack,{ok:true,roomId:existing.id,broadcasterToken:existing.token,dailyUrl:existing.dailyRoomUrl,dailyToken:await createDailyToken(existing.dailyRoomName,"broadcaster",socket.id),live:existing.live,viewers:existing.viewers.size});}catch(error){console.error("Daily token error",error);return safeAck(ack,{ok:false,error:"Não foi possível preparar a transmissão."});}}if(!allowed(socket,5,60_000))return safeAck(ack,{ok:false,error:"Muitas tentativas. Aguarde um minuto."});try{const roomId=rooms.newId(),daily=await createDailyRoom(roomId),room=rooms.create(roomId,socket.id,daily.name,daily.url),dailyToken=await createDailyToken(room.dailyRoomName,"broadcaster",socket.id);socket.join(room.id);safeAck(ack,{ok:true,roomId:room.id,broadcasterToken:room.token,dailyUrl:room.dailyRoomUrl,dailyToken,viewers:0});}catch(error){console.error("Daily room creation error",error);safeAck(ack,{ok:false,error:"Não foi possível criar a sala de transmissão."});}});
    socket.on("reclaim-room",async(input:unknown,ack:Ack)=>{if(!allowed(socket))return;const data=input as {roomId?:unknown;token?:unknown};if(!validRoomId(data?.roomId)||typeof data.token!=="string")return safeAck(ack,{ok:false,error:"Credenciais inválidas."});const room=rooms.reclaim(data.roomId,data.token,socket.id);if(!room)return safeAck(ack,{ok:false,error:"Sala expirada ou credenciais inválidas."});try{const dailyToken=await createDailyToken(room.dailyRoomName,"broadcaster",socket.id);socket.join(room.id);safeAck(ack,{ok:true,roomId:room.id,dailyUrl:room.dailyRoomUrl,dailyToken,live:room.live,viewers:room.viewers.size});io.to([...room.viewers]).emit("room-state",{live:room.live,count:room.viewers.size});}catch(error){console.error("Daily token error",error);safeAck(ack,{ok:false,error:"Não foi possível retomar a transmissão."});}});
    socket.on("join-room",async(input:unknown,ack:Ack)=>{if(!allowed(socket))return;const id=(input as {roomId?:unknown})?.roomId;if(!validRoomId(id))return safeAck(ack,{ok:false,error:"Código de sala inválido."});const room=rooms.get(id);if(!room)return safeAck(ack,{ok:false,error:"Sala não encontrada."});try{const dailyToken=await createDailyToken(room.dailyRoomName,"viewer",socket.id),previous=rooms.findByViewer(socket.id);if(previous&&previous.id!==id){previous.viewers.delete(socket.id);socket.leave(previous.id);}room.viewers.add(socket.id);socket.join(id);safeAck(ack,{ok:true,live:room.live,dailyUrl:room.dailyRoomUrl,dailyToken});io.to(room.broadcasterId).emit("viewer-count",{count:room.viewers.size});io.to([...room.viewers]).emit("room-state",{live:room.live,count:room.viewers.size});}catch(error){console.error("Daily viewer token error",error);safeAck(ack,{ok:false,error:"Não foi possível entrar na transmissão."});}});
    socket.on("leave-room",(input:unknown)=>{const id=(input as {roomId?:unknown})?.roomId;if(!validRoomId(id))return;const room=rooms.get(id);if(!room)return;room.viewers.delete(socket.id);socket.leave(id);io.to(room.broadcasterId).emit("viewer-count",{count:room.viewers.size});io.to([...room.viewers]).emit("room-state",{live:room.live,count:room.viewers.size});});
    socket.on("broadcast-started",(input:unknown)=>{if(!allowed(socket))return;const id=(input as {roomId?:unknown})?.roomId;if(!validRoomId(id)||!rooms.isBroadcaster(id,socket.id))return;const room=rooms.get(id)!;room.live=true;socket.to(id).emit("broadcast-started");socket.to(id).emit("room-state",{live:true,count:room.viewers.size});});
    socket.on("broadcast-ended",(input:unknown)=>{const id=(input as {roomId?:unknown})?.roomId;if(!validRoomId(id)||!rooms.isBroadcaster(id,socket.id))return;const room=rooms.get(id)!;room.live=false;socket.to(id).emit("broadcast-ended");socket.to(id).emit("room-state",{live:false,count:room.viewers.size});});
    socket.on("disconnect",()=>{const broadcast=rooms.findByBroadcaster(socket.id);if(broadcast){broadcast.live=false;io.to([...broadcast.viewers]).emit("broadcaster-disconnected");rooms.scheduleBroadcasterRemoval(broadcast.id,room=>{io.to([...room.viewers]).emit("broadcast-ended");void deleteDailyRoom(room.dailyRoomName);});}const viewed=rooms.findByViewer(socket.id);if(viewed){viewed.viewers.delete(socket.id);io.to(viewed.broadcasterId).emit("viewer-count",{count:viewed.viewers.size});io.to([...viewed.viewers]).emit("room-state",{live:viewed.live,count:viewed.viewers.size});}});
  });
  return rooms;
}
