import { memo, useMemo } from "react";
import { Activity, Cpu, Gauge, Volume2, VolumeX } from "lucide-react";
const MetricCard=memo(function MetricCard({icon:Icon,label,value,suffix,bars}:{icon:React.ElementType;label:string;value:string|number;suffix?:string;bars:number[]}){
  return <div className="group min-w-0 cursor-pointer rounded-xl border border-zinc-800/60 bg-[#121216]/80 px-3.5 py-3 shadow-sm backdrop-blur-xl transition-all duration-200 ease-out hover:-translate-y-0.5 hover:border-purple-500/40 hover:bg-[#16161c] hover:shadow-lg hover:shadow-purple-500/5"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2 text-zinc-500"><Icon size={14}/><span className="text-[10px] font-medium uppercase tracking-[.13em]">{label}</span></div><span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,.35)]"/></div><div className="flex items-end justify-between gap-3"><div><span className="text-lg font-semibold tracking-tight text-zinc-100">{value}</span>{suffix&&<span className="ml-1 text-[11px] text-zinc-500">{suffix}</span>}</div><div className="flex h-7 items-end gap-[3px]">{bars.map((height,index)=><span key={index} className="w-[3px] rounded-full bg-purple-500/50 transition-colors group-hover:bg-purple-500/80" style={{height:`${height}%`}}/>)}</div></div></div>;
});
export const StatsPanel=memo(function StatsPanel({open,cpu,latency,bitrate,systemAudio}:{open:boolean;cpu:number;latency:string|number;bitrate:string|number;systemAudio:boolean}){
  const cpuBars=useMemo(()=>[26,41,33,52,46,58,40,Math.max(12,Math.min(90,cpu+20))],[cpu]);
  const audioBars=useMemo(()=>systemAudio?[24,55,38,74,44,64,79,58]:[5,5,5,5,5,5,5,5],[systemAudio]);
  return <div className={`relative z-30 shrink-0 overflow-hidden border-b border-zinc-800/60 bg-[#09090b]/64 backdrop-blur-xl transition-all duration-300 transform-gpu ${open?"max-h-32 translate-y-0 opacity-100":"max-h-0 -translate-y-2 border-b-transparent opacity-0"}`} style={{willChange:"transform,opacity,max-height"}}><section className="grid grid-cols-4 gap-2 px-5 py-3"><MetricCard icon={Cpu} label="CPU" value={Math.round(cpu)} suffix="%" bars={cpuBars}/><MetricCard icon={Activity} label="Latência" value={latency} suffix={latency==="—"?"":"ms"} bars={[42,35,49,30,39,45,36,43]}/><MetricCard icon={Gauge} label="Bitrate" value={bitrate} suffix={bitrate==="—"?"":"Mbps"} bars={[31,46,51,63,71,67,76,73]}/><MetricCard icon={systemAudio?Volume2:VolumeX} label="Áudio do sistema" value={systemAudio?"Ativo":"Mudo"} bars={audioBars}/></section></div>;
});
